# This rule is not used by the project nfs-server-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the sharedvolume.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: nfs-server-controller
    app.kubernetes.io/managed-by: kustomize
  name: nfsserver-editor-role
rules:
- apiGroups:
  - sharedvolume.io
  resources:
  - nfsservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sharedvolume.io
  resources:
  - nfsservers/status
  verbs:
  - get
