name: Bug Report
description: Create a report to help us improve
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear and concise description of what the bug is.
      placeholder: Tell us what you see!
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Apply this manifest '...'
        2. Run this command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: |
        Please provide information about your environment:
      placeholder: |
        - Kubernetes version: 
        - NFS Server Controller version: 
        - Platform (AWS, GCP, Azure, bare metal, etc.): 
        - Storage class used: 
      render: text
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant logs
      description: Please copy and paste any relevant controller logs.
      render: shell

  - type: textarea
    id: manifests
    attributes:
      label: Relevant manifests
      description: Please copy and paste any relevant Kubernetes manifests (sanitize sensitive data).
      render: yaml

  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
